version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    volumes:
      - stats-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main:
    build: main
    container_name: main
    ports:
      - "8081:8080"
    depends_on:
      - stats-server
      - main-db
    environment:
      - spring.datasource.url=jdbc:postgresql://ewm-db:5432/ewm-db
      - spring.datasource.username=postgres
      - spring.datasource.password=pass