version: '3.8'
services:
  stats-db:
    image: postgres:15.2-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass

  stats-server:
    build: stats-service/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db

  ewm-db:
    image: postgres:15.2-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass

  ewm-service:
    build: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-db
      - STATS_SERVER_URL=http://stats-server:9090



